- hosts: mysql-s
  become: true
  tasks:
          #    - name: Update apt package
          #      ansible.builtin.shell: "apt update"
   
    - name: Set up the repo for mysql 8
      ansible.builtin.get_url:
        url:  "https://dev.mysql.com/get/mysql-apt-config_0.8.19-1_all.deb" 
        dest: /tmp/mysql-apt-config_0.8.19-1_all.deb

    - name: Configuring mysql-apt-config
      ansible.builtin.debconf:
        name: mysql-community-server
        question: Configuring mysql-apt-config
        value: <ok>
        vtype: select

    - name: Configuring mysql-apt-config
      ansible.builtin.debconf:
        name: mysql-community-server
        question: Which MySQL product do you wish to configure?
        value: ok
        vtype: select

    - name: Install the downloaded deb file
      ansible.builtin.shell: "dpkg -i /tmp/mysql-apt-config_0.8.19-1_all.deb"
    
    - name: Add GPG Key
      ansible.builtin.shell: "apt-key adv --keyserver pgp.mit.edu --recv-keys 3A79BD29"
      register: apt_key_install
      until: apt_key_install is succeeded

