---
  - name: remove old phpmyadmin
    ansible.builtin.package:
      package: "{{ item }}"
      state: absent
    loop:
      - phpmyadmin

  - name: add PHP Repository
    ansible.builtin.shell: |
      add-apt-repository -y ppa:ondrej/php

  - name: update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: install requirement service
    ansible.builtin.package:
      package: "{{ item }}"
      state: present
    loop:
      - php8.0
      - php8.0
      - php8.0-cli
      - php8.0-common
      - php8.0-curl
      - php8.0-gd
      - php8.0-intl
      - php8.0-mbstring
      - php8.0-mysql
      - php8.0-opcache
      - php8.0-readline
      - php8.0-xml
      - php8.0-xsl
      - php8.0-zip
      - php8.0-bz2
      - libapache2-mod-php8.0

  - name: create directory for phpMyAdmin
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0777' 
    loop:
      - /usr/share/phpmyadmin/tmp
      - /etc/phpmyadmin
      - /var/lib/phpmyadmin/tmp

  - name: download latest version of phpMyAdmin 
    ansible.builtin.unarchive:
      src: 'https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-english.tar.gz'
      dest: '/tmp'
      owner: 'root'
      group: 'root'
      remote_src: yes
    register: package_download
    until: package_download is succeeded
    
  - name: mv folder with new name
    ansible.builtin.shell: |
            mv /tmp/phpMyAdmin-5.2.0-english/* /usr/share/phpmyadmin
    ignore_errors: yes

  - name: create phpMyAdmin configuration file
    ansible.builtin.copy:
      src: '/usr/share/phpmyadmin/config.sample.inc.php'
      dest: '/usr/share/phpmyadmin/config.inc.php'
      owner: 'root'
      group: 'root'
      remote_src: yes

  - name: update phpmyadmin config.inc.php 
    ansible.builtin.replace:
      path: '/usr/share/phpmyadmin/config.inc.php'
      regexp: \$cfg\['blowfish_secret'\] \= '';
      replace: $cfg['blowfish_secret'] = 'H2OxcGXxflSd8JwrwVlh6KW6s2rER63i';
      backup: yes

  - name: update phpmyadmin config.inc.php
    ansible.builtin.lineinfile:
      path: '/usr/share/phpmyadmin/config.inc.php'
      regexp: declare(strict_types=1); 
      line: $cfg['TempDir'] = '/var/lib/phpmyadmin/tmp';
      backup: yes

  - name: restart apache2 service
    ansible.builtin.service:
      name: apache2
      state: restarted
      enabled: yes

