- hosts: mysql-s
  become: true
  tasks:
    - name: Wget the repo for mysql 8
      ansible.builtin.shell: "wget -c https://repo.mysql.com//mysql-apt-config_0.8.13-1_all.deb"

    - name: Set up the repo for mysql 8
      ansible.builtin.shell: "sudo dpkg -i mysql-apt-config_0.8.13-1_all.deb"

    - name: Add GPG Key
      ansible.builtin.shell: "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 467B942D3A79BD29"

    - name: Update ATP
      ansible.builtin.shell: "sudo apt update"

    - name: Install mysql 8
      ansible.builtin.shell: "sudo apt-get install mysql-server"

      #    - name: Set up the repo for mysql 8
      #      ansible.builtin.get_url:
      #        url:  "https://dev.mysql.com/get/mysql-apt-config_0.8.19-1_all.deb" 
      #        dest: /tmp/mysql-apt-config_0.8.19-1_all.deb
      #
      #    - name: Configuring mysql-apt-config
      #      ansible.builtin.debconf:
      #        name: mysql-community-server
      #        question: Configuring mysql-apt-config
      #        value: <ok>
      #        vtype: select
      #
      #    - name: Configuring mysql-apt-config
      #      ansible.builtin.debconf:
      #        name: mysql-community-server
      #        question: Which MySQL product do you wish to configure?
      #        value: ok
      #        vtype: select
      #
      #    - name: Install the downloaded deb file
      #      ansible.builtin.shell: "dpkg -i /tmp/mysql-apt-config_0.8.19-1_all.deb"
      #    
      #    - name: Add GPG Key
      #      ansible.builtin.shell: "apt-key adv --keyserver pgp.mit.edu --recv-keys 3A79BD29"
      #      register: apt_key_install
      #      until: apt_key_install is succeeded

